const dummyProgram = {
  title: "Beginner Strength Program",
  description: "3-week strength program for beginners, 5 days/week.",
  weeks: [
    {
      orderIndex: 1,
      days: [
        {
          orderIndex: 1,
          exercises: [
            {
              orderIndex: 1,
              title: "Machine Leg Extension",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 20,
            },
            {
              orderIndex: 2,
              title: "Goblet Squat",
              targetSets: 3,
              targetReps: 10,
              metric: "Kilos",
              targetValue: 12,
            },
            {
              orderIndex: 3,
              title: "Assisted Pullup",
              targetSets: 3,
              targetReps: 8,
              metric: "Kilos",
              targetValue: 25,
            },
            {
              orderIndex: 4,
              title: "Cable Curl",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 7,
            },
          ],
        },
        {
          orderIndex: 2,
          exercises: [
            {
              orderIndex: 1,
              title: "Machine Press",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 30,
            },
            {
              orderIndex: 2,
              title: "Incline Sprint",
              targetSets: 4,
              targetReps: 1,
              metric: "Meters",
              targetValue: 50,
            },
            {
              orderIndex: 3,
              title: "Dumbbell Bench Press",
              targetSets: 3,
              targetReps: 10,
              metric: "Kilos",
              targetValue: 10,
            },
            {
              orderIndex: 4,
              title: "Rope Pushdown",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 10,
            },
          ],
        },
        {
          orderIndex: 3,
          exercises: [
            {
              orderIndex: 1,
              title: "Trap Bar Deadlift",
              targetSets: 3,
              targetReps: 8,
              metric: "Kilos",
              targetValue: 40,
            },
            {
              orderIndex: 2,
              title: "Lying Leg Curl",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 15,
            },
            {
              orderIndex: 3,
              title: "Seated Machine Row",
              targetSets: 3,
              targetReps: 10,
              metric: "Kilos",
              targetValue: 20,
            },
            {
              orderIndex: 4,
              title: "Dumbbell Standing",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 7,
            },
          ],
        },
        {
          orderIndex: 4,
          exercises: [
            {
              orderIndex: 1,
              title: "Barbell Bench Press",
              targetSets: 3,
              targetReps: 8,
              metric: "Kilos",
              targetValue: 30,
            },
            {
              orderIndex: 2,
              title: "Wide Grip Lat Pulldown",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 25,
            },
            {
              orderIndex: 3,
              title: "Dumbbell Press",
              targetSets: 3,
              targetReps: 10,
              metric: "Kilos",
              targetValue: 10,
            },
            {
              orderIndex: 4,
              title: "EZ Bar Curl",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 12,
            },
          ],
        },
        {
          orderIndex: 5,
          exercises: [
            {
              orderIndex: 1,
              title: "Back Squat",
              targetSets: 3,
              targetReps: 8,
              metric: "Kilos",
              targetValue: 30,
            },
            {
              orderIndex: 2,
              title: "Standing Machine",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 20,
            },
            {
              orderIndex: 3,
              title: "Ergometer Row",
              targetSets: 3,
              targetReps: 1,
              metric: "Meters",
              targetValue: 500,
            },
            {
              orderIndex: 4,
              title: "Straight Bar Pushdown",
              targetSets: 3,
              targetReps: 12,
              metric: "Kilos",
              targetValue: 10,
            },
          ],
        },
      ],
    },
  ],
};

const dummyEquipments = [
  "dumbbell",
  "weight plate",
  "barbell",
  "sled",
  "dip station",
  "rack",
  "plate tree/plate storage rack",
  "kettlebell",
  "medicine ball",
  "yoga mat",
  "rowing machine",
];
module.exports = {
  dummyEquipments,
  dummyProgram,
};
