const EQUIPMENTS_SEED = [
  "Treadmill",
  "Stationary Bike",
  "Recumbent Bike",
  "Air Bike",
  "Elliptical",
  "Rowing Ergometer",
  "Stair Climber",
  "SkiErg",
  "Vertical Climber",
  "Arc Trainer",
  "Spin Bike",

  "Power Rack",
  "Half Rack",
  "Squat Stands",
  "Smith Machine",
  "Functional Trainer",
  "Cable Column",
  "Cable Crossover",
  "Pull-Up Bar",
  "Dip Station",
  "Roman Chair",
  "Hyperextension Bench",
  "GHD Bench",
  "Weightlifting Platform",
  "Squat Rack",

  "Flat Bench",
  "Adjustable Bench",
  "Olympic Flat Bench",
  "Olympic Incline Bench",
  "Olympic Decline Bench",
  "Preacher Curl Bench",
  "Sissy Squat Bench",

  // --- STRENGTH: MACHINES (Hardware Footprints) ---
  "Chest Press Machine",
  "Pec Deck / Rear Delt Combo",
  "Shoulder Press Machine",
  "Lateral Raise Machine",
  "Lat Pulldown Machine",
  "Seated Row Machine",
  "Assisted Pull-Up / Dip Machine",
  "Leg Press Machine",
  "Hack Squat Machine",
  "Leg Extension Machine",
  "Leg Curl Machine",
  "Adductor / Abductor Combo",
  "Hip Thrust Machine",
  "Calf Raise Machine",
  "Glute Kickback Machine",
  "Belt Squat Machine",
  "Pullover Machine",
  "T-Bar Row Station",
  "Landmine Base",
  "Back Extension Machine",
  "Ab Crunch Machine",
  "Seated Dip Machine",

  "Olympic Barbell",
  "EZ Curl Bar",
  "Trap Bar",
  "Dumbbell",
  "Kettlebell",
  "Medicine Ball",
  "Slam Ball",
  "Sandbag",
  "Steel Mace",
  "Weight Plates",
  "Bumper Plates",

  "Sled / Prowler",
  "Battle Ropes",
  "Suspension Trainer",
  "Gymnastic Rings",
  "Plyo Box",
  "Step Platform",
  "Resistance Band Set",
  "Ab Wheel",
  "Stability Ball",
  "Bosu Ball",
  "Yoga Mat",
  "Foam Roller",
  "Weight Vest",
  "Dip Belt",
  "Jump Rope",
  "Boxing Gloves / Punching Bag",
  "TRX Trainer",
  "Landmine Attachment",

  "Farmers Walk Handles",
  "Yoke",
  "Log Bar",
  "Atlas Stone",
  "Tire Flip Station",
];

module.exports = EQUIPMENTS_SEED;
